No silent bootstrapping

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -21,7 +21,6 @@ else
 fi
 
 echo -n "[RAKE] $rake_task "
-rake $rake_task >/dev/null 2>error.log || ( echo -e "FAILED\n\nAn error occurred during run of rake-task \"$rake_task\". Run \`rake $rake_task\` yourself."; output_error_log; exit 1 )
+rake $rake_task
+#rake $rake_task >/dev/null 2>error.log || ( echo -e "FAILED\n\nAn error occurred during run of rake-task \"$rake_task\". Run \`rake $rake_task\` yourself."; output_error_log; exit 1 )
 echo OK
-
-cat error.log
