Improved version of bootstrap script

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -1,9 +1,25 @@
-#!/bin/sh
+#!/bin/bash
 
-gem install rake
+set -e
+
+echo -n '[CHECK] ruby installed? '
+which 'ruby' >/dev/null 2>&1 || ( echo -e "FAILED\n\nCould not find \`ruby\`. Please install ruby or add it to PATH"; exit 1 )
+echo OK
+
+echo -n '[CHECK] go installed? '
+which 'go'  >/dev/null 2>&1 || ( echo -e "FAILED\n\nCould not find \`go\`. Please install go or add it to PATH"; exit 1 )
+echo OK
+
+echo -n '[INSTALL] rubygem "rake" '
+gem install rake >/dev/null 2>&1 || ( echo -e "FAILED\n\nAn error occurred during installation of rake. Run \`gem install rake\` yourself."; exit 1 )
+echo OK
 
 if [ -n "$CI" ]; then
-  rake bootstrap:ci
+  rake_task='bootstrap:ci'
 else
-  rake bootstrap
+  rake_task='bootstrap'
 fi
+
+echo -n "[RAKE] $rake_task "
+rake $rake_task >/dev/null 2>&1 || ( echo -e "FAILED\n\nAn error occurred during run of rake-task \"$rake_task\". Run \`rake $rake_task\` yourself."; exit 1 )
+echo OK
